# -*- coding: utf-8 -*-
"""bloom-distillation-v3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19c9j0O8n_1CBi7cTVbM9Q1LByRFPZVz_
"""

import sys
import transformers
import torch
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import BloomTokenizerFast, BloomForSequenceClassification

teacher_model_path = sys.argv[1]
training_data_path = sys.argv[2]
save_directory = sys.argv[3]

#load the training data
#!gsutil cp gs://training_dataset_bloom/merged_symp_icd/symptoms_icd10.json ./training_data.jsonl
training_data = pd.read_json(training_data_path, lines=True)

# Load the teacher model
#!gsutil -m cp -r "gs://finetunned_760m_bloom/bloom_icd_10/finetuned_model/*" "/content/finetuned_model/"
tokenizer = BloomTokenizerFast.from_pretrained(teacher_model_path, repo_type="local")
teacher_model = BloomForSequenceClassification.from_pretrained(teacher_model_path)

label_encoder = LabelEncoder()
training_data ['encoded_labels'] = label_encoder.fit_transform(training_data['icd10_code'])

train_data, test_data = train_test_split(training_data, test_size=0.1)

# reset the indices
train_data = train_data.reset_index(drop=True)
test_data = test_data.reset_index(drop=True)

class SimpleNN(nn.Module):
    def __init__(self, input_size, num_classes):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(input_size, 512)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(512, num_classes)  # Output layer

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

# Assuming input size and number of classes are known
input_size = 1536
num_classes = train_data['icd10_code'].nunique()
student_model = SimpleNN(input_size, num_classes)
# model is by default on CPU

class CustomDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=1536):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

        # Encode string labels to integers
        self.label_encoder = LabelEncoder()
        self.encoded_labels = self.label_encoder.fit_transform(labels)

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        # Tokenize the text
        encoded = self.tokenizer.encode_plus(
            self.texts[idx],
            add_special_tokens=True,
            return_tensors='pt',
            padding='max_length',
            truncation=True,
            max_length=self.max_length
        )
        input_ids = encoded['input_ids'].flatten()

        # Ensure input_ids is the correct shape
        if len(input_ids) != self.max_length:
            padding = [0] * (self.max_length - len(input_ids))
            input_ids = torch.cat((input_ids, torch.tensor(padding)), dim=0)

        # Fetch the corresponding encoded label
        label = self.encoded_labels[idx]

        return input_ids, label


train_dataset = CustomDataset(train_data['symptoms'], train_data['icd10_code'], tokenizer)
train_dataloader = DataLoader(train_dataset, batch_size=8, shuffle=True)

# Loss and Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(student_model.parameters(), lr=0.001)

train_data.reset_index(drop=True, inplace=True)

num_epochs = 3

for epoch in range(num_epochs):
    for batch in train_dataloader:
        input_ids, labels = batch

        # Ensure input_ids and labels are of the correct type
        input_ids = input_ids.float()
        labels = torch.tensor(labels, dtype=torch.long)

        # Forward pass
        outputs = student_model(input_ids)
        loss = criterion(outputs, labels)

        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

# Prepare validation dataset
test_dataset = CustomDataset(test_data['symptoms'], test_data['icd10_code'], tokenizer)
test_dataloader = DataLoader(test_dataset, batch_size=8, shuffle=True)

# Validation Function
def validate(model, dataloader, criterion):
    model.eval()  # Set the model to evaluation mode
    total_loss, total_correct, total_samples = 0, 0, 0

    with torch.no_grad():
        for batch in dataloader:
            input_ids, labels = batch
            input_ids = input_ids.float()
            labels = torch.tensor(labels, dtype=torch.long)

            # Forward pass
            outputs = model(input_ids)
            loss = criterion(outputs, labels)
            total_loss += loss.item()

            # Calculate accuracy
            _, predicted = torch.max(outputs.data, 1)
            total_samples += labels.size(0)
            total_correct += (predicted == labels).sum().item()

    avg_loss = total_loss / len(dataloader)
    accuracy = total_correct / total_samples
    return avg_loss, accuracy

# Training loop with validation
num_epochs = 30

for epoch in range(num_epochs):
    # Training
    student_model.train()
    for batch in train_dataloader:
        input_ids, labels = batch
        input_ids = input_ids.float()
        labels = torch.tensor(labels, dtype=torch.long)

        # Forward pass
        outputs = student_model(input_ids)
        loss = criterion(outputs, labels)

        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    # Validation
    val_loss, val_accuracy = validate(student_model, test_dataloader, criterion)
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}, Validation Loss: {val_loss:.4f}, Validation Accuracy: {val_accuracy:.4f}')

test_prompt = "i have red spots in my face"

# Tokenize the test prompt
encoded_test_prompt = tokenizer.encode_plus(
    test_prompt,
    add_special_tokens=True,
    return_tensors='pt',
    padding='max_length',
    truncation=True,
    max_length=1536
)
input_ids_test = encoded_test_prompt['input_ids'].flatten()

# Ensure the input is the correct shape
input_ids_test = input_ids_test.unsqueeze(0)  # Add batch dimension

# Make sure the model is in evaluation mode
student_model.eval()

with torch.no_grad():
    # Forward pass
    output = student_model(input_ids_test.float())
    prediction = torch.argmax(output, dim=1)
    predicted_label = label_encoder.inverse_transform(prediction.numpy())

print("Predicted Label:", predicted_label[0])

#first save the model locally
#save_directory = "/content/distilled_model"
torch.save(student_model.state_dict(), save_directory)

#save the model in a bucket in GCP
#!gsutil cp -r /content/distilled_model gs://finetunned_destillation/destilled_bloom_icd_10/

