# container to deploy service.py
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install necessary libraries
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container
COPY . .

CMD ["sh", "-c", "uvicorn service:app --host 0.0.0.0 --port ${PORT}"]
